---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mike/public_html/

    - /usr/local/bin/npm ci
    - /usr/local/bin/npm run build

    - /bin/rsync -a --exclude='.git' --exclude='node_modules' dist/ $DEPLOYPATH
